---
id: rubykansai81-octopress-to-jekyll
base_name: octopress-to-jekyll
tags:
- jekyll
presentation_date: 2018/03/17
version: 2018.03.17
licenses: []
slideshare_id: octopress-2-github-pages-jekyll-3-amp-netlify
speaker_deck_id: buroguwo-octopress-2-plus-github-pages-kara-jekyll-3-plus-amp-plus-netlify-niyi-xing-sitahua
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
