---
id: rubykansai81-octopress-to-jekyll
base_name: octopress-to-jekyll
tags:
- jekyll
presentation_date: 2018/03/17
version: 2018.03.17
licenses: []
slideshare_id:
speaker_deck_id:
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
